# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gdi-node-api-chart.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.api }}
      targetPort: api
      protocol: TCP
  selector:
    app: {{ include "gdi-node-api-chart.fullname" . }}
