# templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-config
  namespace: {{ .Values.global.namespace }}
data:
  minio-config.sh: |
    #!/bin/sh
    set -u

    mc -q config host add gdi-storage "$MINIO_SERVER_URL" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASS"

    echo "[STEP 1/2] Making sure that the buckets exist."
    mc -q mb "gdi-storage/$MINIO_APP_BUCKET"
    mc -q mb "gdi-storage/$MINIO_EXT_BUCKET"
    mc -q mb "gdi-storage/$MINIO_BACKUP_BUCKET"

    echo "[STEP 2/2] Making sure that user '$MINIO_APP_USER' exists with the right policy."
    mc -q admin user add gdi-storage "$MINIO_APP_USER" "$MINIO_APP_PASS"
    mc -q admin policy create gdi-storage gdi-node-app-policy /opt/config/gdi-node-app-policy.json
    mc -q admin policy attach gdi-storage gdi-node-app-policy --user "$MINIO_APP_USER"

    echo "Done: Minio storage is configured."

  gdi-node-app-policy.json: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
          ],
          "Resource": "arn:aws:s3:::gdi-node-storage/*"
        },
        {
          "Effect": "Allow",
          "Action": [
            "s3:ListBucket",
            "s3:GetObject",
            "s3:PutObject",
            "s3:DeleteObject"
          ],
          "Resource": "arn:aws:s3:::gdi-node-backup/*"
        },
        {
          "Effect": "Allow",
          "Action": ["s3:ListBucket", "s3:GetObject"],
          "Resource": "arn:aws:s3:::gdi-data-provider/*"
        }
      ]
    }
