apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres-chart.fullname" . }}-sql-scripts
  namespace: {{ .Values.global.namespace }}
data:
  V1.0.0.0__Init_schema_user.sql: |
    {{ .Files.Get "sql-queries/V1.0.0.0__Init_schema_user.sql" | nindent 4 }}
  V1.0.0.1__Create_node-session_tables.sql: |
    {{ .Files.Get "sql-queries/V1.0.0.1__Create_node-session_tables.sql" | nindent 4 }}
  afterMigrate__Reset_permissions.sql: |
    {{ .Files.Get "sql-queries/afterMigrate__Reset_permissions.sql" | nindent 4 }}
