apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "postgres-chart.fullname" . }}-init
  namespace: {{ .Values.global.namespace }}
spec:
  template:
    spec:
      containers:
        - name: database-init
          image: flyway/flyway:10.17-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              until pg_isready -h {{ include "postgres-chart.fullname" . }}-{{ .Values.global.namespace }} -p {{ .Values.service.port }} -d {{ .Values.postgresql.db }}; do
                echo waiting for database
                sleep 2
              done
              flyway migrate
          env:
            - name: FLYWAY_URL
              value: {{ printf "jdbc:postgresql://%s-%s.%s.svc.cluster.local:%d/%s" (include "postgres-chart.fullname" .) .Values.global.namespace .Values.service.port .Values.postgresql.db }}
            - name: FLYWAY_SCHEMAS
              value: {{ .Values.postgresql.schema }}
            - name: FLYWAY_USER
              value: {{ .Values.postgresql.user }}
            - name: FLYWAY_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: FLYWAY_PLACEHOLDERS_APP_USER
              value: {{ .Values.postgresql.appUser }}
            - name: FLYWAY_PLACEHOLDERS_APP_PASS
              value: {{ .Values.postgresql.appPassword }}
          volumeMounts:
            - name: flyway-sql
              mountPath: /flyway/sql
      restartPolicy: Never
      volumes:
        - name: flyway-sql
          configMap:
            name: {{ include "postgres-chart.fullname" . }}-sql-scripts
  backoffLimit: 4
