version: '3.8'

services:
  resource-lister:
    build: .
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_REGIONS=${AWS_REGIONS}
    volumes:
      - .:/usr/src/app
    entrypoint: ["/bin/bash", "/usr/src/app/entrypoint.sh"]
