# templates/app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lsaai-chart.fullname" . }}-app
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ include "lsaai-chart.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "lsaai-chart.fullname" . }}-app
    spec:
      containers:
        - name: lsaai
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          ports:
            - containerPort: {{ .Values.app.port }}
          volumeMounts:
            - name: config
              mountPath: /etc/lsaai-mock
      volumes:
        - name: config
          configMap:
            name: {{ include "lsaai-chart.fullname" . }}-app-config
