apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vault-chart.fullname" . }}
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "vault-chart.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "vault-chart.fullname" . }}
    spec:
      containers:
        - name: vault
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["vault", "server", "-config=/vault/config/config.json"]
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: {{ .Values.vault.rootToken }}
          volumeMounts:
            - name: config
              mountPath: "/vault/config"
              readOnly: true
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: config
          configMap:
            name: {{ include "vault-chart.fullname" . }}-config
